FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/app
RUN mkdir locale

RUN install_packages boinc-client boinctui htop
  
COPY *.xml ./

COPY gui_rpc_auth.cfg ./

COPY start.sh ./

CMD ["/bin/bash","/usr/app/start.sh"]