FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/app

RUN install_packages boinc-client boinctui xml-twig-tools htop 

COPY account_boinc.bakerlab.org_rosetta.xml.template ./
COPY *.xml ./
COPY gui_rpc_auth.cfg ./

COPY start*.sh ./

CMD ["/bin/bash","/usr/app/start.sh"]
