FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/app

RUN install_packages boinc-client boinctui xml-twig-tools htop 
  
COPY *.xml ./boinc/
COPY gui_rpc_auth.cfg ./boinc/

COPY start.sh ./

CMD ["/bin/bash","/usr/app/start.sh"]
