FROM balenalib/%%BALENA_ARCH%%-debian-golang as builder

WORKDIR /usr/src/app

RUN go get github.com/godbus/dbus

COPY main.go ./

RUN go build -ldflags "-linkmode external -extldflags -static" -a main.go

FROM scratch
COPY --from=builder /usr/src/app/main /main
CMD ["/main"]
