FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/app

RUN install_packages \
    boinctui \
    kbd
RUN curl -LO https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
RUN tar xfzv gotty_linux_amd64.tar.gz

COPY boinctui.cfg /root/.boinctui.cfg
COPY start.sh ./
RUN chmod u+x start.sh

CMD ["/usr/app/start.sh"]